// frontend/src/components/ui/Pagination.tsx
import { motion } from 'framer-motion';

interface PaginationProps {
  current: number;
  total: number;
  pageSize?: number;
  onChange: (page: number) => void;
}

export default function Pagination({ current, total, pageSize = 20, onChange }: PaginationProps) {
  const totalPages = Math.max(1, Math.ceil(total / pageSize));
  const pages: number[] = [];

  const add = (n: number) => {
    if (n >= 1 && n <= totalPages && !pages.includes(n)) pages.push(n);
  };

  add(1);
  add(totalPages);
  add(current);
  add(current - 1);
  add(current + 1);
  add(current - 2);
  add(current + 2);
  pages.sort((a, b) => a - b);

  const items: (number | '...')[] = [];
  let prev = 0;
  for (const p of pages) {
    if (p - prev > 1) items.push('...');
    items.push(p);
    prev = p;
  }

  return (
    <div className="flex items-center gap-1">
      <button
        className="px-2 py-1 text-[10px] font-bold tracking-wider"
        style={{
          color: current <= 1 ? 'rgba(247,243,232,0.2)' : '#FFF8EE',
          fontFamily: 'var(--font-mono)',
          cursor: current <= 1 ? 'not-allowed' : 'pointer',
        }}
        onClick={() => current > 1 && onChange(current - 1)}
        disabled={current <= 1}
        data-cursor-hover={current > 1 ? true : undefined}
      >
        &lt;
      </button>

      {items.map((item, idx) =>
        item === '...' ? (
          <span
            key={`dot-${idx}`}
            className="px-1 text-[10px]"
            style={{ color: 'rgba(247,243,232,0.3)', fontFamily: 'var(--font-mono)' }}
          >
            ...
          </span>
        ) : (
          <motion.button
            key={item}
            className="px-2.5 py-1 text-[10px] font-bold tracking-wider min-w-[28px]"
            style={{
              backgroundColor: current === item ? '#F5A623' : 'transparent',
              color: current === item ? '#1A1612' : '#FFF8EE',
              fontFamily: 'var(--font-mono)',
              border: current === item ? 'none' : '1px solid rgba(247,243,232,0.1)',
            }}
            onClick={() => onChange(item)}
            whileHover={current !== item ? { scale: 1.1, backgroundColor: 'rgba(245,166,35,0.15)' } : {}}
            whileTap={{ scale: 0.95 }}
            data-cursor-hover
          >
            {item}
          </motion.button>
        )
      )}

      <button
        className="px-2 py-1 text-[10px] font-bold tracking-wider"
        style={{
          color: current >= totalPages ? 'rgba(247,243,232,0.2)' : '#FFF8EE',
          fontFamily: 'var(--font-mono)',
          cursor: current >= totalPages ? 'not-allowed' : 'pointer',
        }}
        onClick={() => current < totalPages && onChange(current + 1)}
        disabled={current >= totalPages}
        data-cursor-hover={current < totalPages ? true : undefined}
      >
        &gt;
      </button>
    </div>
  );
}

// frontend/src/components/Pagination.vue
<template>
  <div class="pagination">
    <button
      class="page-btn"
      :disabled="currentPage <= 1"
      @click="$emit('update:currentPage', currentPage - 1)"
    >
      ←
    </button>
    <button
      v-for="p in visiblePages"
      :key="p"
      class="page-btn"
      :class="{ active: p === currentPage }"
      @click="$emit('update:currentPage', p)"
    >
      {{ p }}
    </button>
    <button
      class="page-btn"
      :disabled="currentPage >= totalPages"
      @click="$emit('update:currentPage', currentPage + 1)"
    >
      →
    </button>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  total: number
  pageSize?: number
  currentPage: number
}
const props = withDefaults(defineProps<Props>(), {
  pageSize: 20
})

defineEmits<{
  'update:currentPage': [page: number]
}>()

const totalPages = computed(() => Math.ceil(props.total / props.pageSize))

const visiblePages = computed(() => {
  const pages: number[] = []
  const maxVisible = 5
  let start = Math.max(1, props.currentPage - Math.floor(maxVisible / 2))
  let end = Math.min(totalPages.value, start + maxVisible - 1)
  if (end - start + 1 < maxVisible) {
    start = Math.max(1, end - maxVisible + 1)
  }
  for (let i = start; i <= end; i++) {
    pages.push(i)
  }
  return pages
})
</script>

<style scoped>
.pagination {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 24px 0;
}
.page-btn {
  min-width: 36px;
  height: 36px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: var(--font-body);
  font-size: 14px;
  color: var(--text-secondary);
  background: transparent;
  border: none;
  border-radius: var(--radius-md);
  cursor: pointer;
  transition: background 0.2s;
}
.page-btn:hover:not(:disabled):not(.active) {
  background: rgba(0, 0, 0, 0.04);
}
.page-btn.active {
  background: var(--text-primary);
  color: var(--text-white);
}
.page-btn:disabled {
  opacity: 0.3;
  cursor: not-allowed;
}
</style>
