// frontend/src/components/Pagination.vue
<template>
  <div class="pagination">
    <button
      class="page-btn"
      :disabled="currentPage <= 1"
      @click="$emit('update:currentPage', currentPage - 1)"
    >
      ←
    </button>
    <button
      v-for="p in visiblePages"
      :key="p"
      class="page-btn"
      :class="{ active: p === currentPage }"
      @click="$emit('update:currentPage', p)"
    >
      {{ p }}
    </button>
    <button
      class="page-btn"
      :disabled="currentPage >= totalPages"
      @click="$emit('update:currentPage', currentPage + 1)"
    >
      →
    </button>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  total: number
  pageSize?: number
  currentPage: number
}
const props = withDefaults(defineProps<Props>(), {
  pageSize: 20
})

defineEmits<{
  'update:currentPage': [page: number]
}>()

const totalPages = computed(() => Math.ceil(props.total / props.pageSize))

const visiblePages = computed(() => {
  const pages: number[] = []
  const maxVisible = 5
  let start = Math.max(1, props.currentPage - Math.floor(maxVisible / 2))
  let end = Math.min(totalPages.value, start + maxVisible - 1)
  if (end - start + 1 < maxVisible) {
    start = Math.max(1, end - maxVisible + 1)
  }
  for (let i = start; i <= end; i++) {
    pages.push(i)
  }
  return pages
})
</script>

<style scoped>
.pagination {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 24px 0;
}
.page-btn {
  min-width: 36px;
  height: 36px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: var(--font-body);
  font-size: 14px;
  color: var(--text-secondary);
  background: transparent;
  border: none;
  border-radius: var(--radius-md);
  cursor: pointer;
  transition: background 0.2s;
}
.page-btn:hover:not(:disabled):not(.active) {
  background: rgba(0, 0, 0, 0.04);
}
.page-btn.active {
  background: var(--text-primary);
  color: var(--text-white);
}
.page-btn:disabled {
  opacity: 0.3;
  cursor: not-allowed;
}
</style>

// frontend/src/components/Pagination.tsx
import { ChevronLeft, ChevronRight } from 'lucide-react'

interface PaginationProps {
  current: number
  total: number
  onChange: (page: number) => void
}

export default function Pagination({ current, total, onChange }: PaginationProps) {
  if (total <= 1) return null

  const pages: (number | string)[] = []
  const maxVisible = 5

  if (total <= maxVisible + 2) {
    for (let i = 1; i <= total; i++) pages.push(i)
  } else {
    pages.push(1)
    if (current > 3) pages.push('...')
    const start = Math.max(2, current - 1)
    const end = Math.min(total - 1, current + 1)
    for (let i = start; i <= end; i++) pages.push(i)
    if (current < total - 2) pages.push('...')
    pages.push(total)
  }

  return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 'var(--spacing-xs)', marginTop: 'var(--spacing-xl)' }}>
      <button
        onClick={() => onChange(current - 1)}
        disabled={current === 1}
        style={{
          width: 36,
          height: 36,
          borderRadius: 'var(--rounded-md)',
          border: '1px solid var(--color-hairline)',
          backgroundColor: 'var(--color-canvas)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          cursor: current === 1 ? 'not-allowed' : 'pointer',
          opacity: current === 1 ? 0.5 : 1,
          color: 'var(--color-ink)',
          transition: 'all 150ms ease',
        }}
      >
        <ChevronLeft size={16} />
      </button>

      {pages.map((p, idx) =>
        p === '...' ? (
          <span key={`dot-${idx}`} style={{ padding: '0 8px', color: 'var(--color-muted-soft)', fontSize: 14 }}>
            ...
          </span>
        ) : (
          <button
            key={p}
            onClick={() => onChange(p as number)}
            style={{
              minWidth: 36,
              height: 36,
              borderRadius: 'var(--rounded-md)',
              border: '1px solid',
              borderColor: current === p ? 'var(--color-primary)' : 'var(--color-hairline)',
              backgroundColor: current === p ? 'var(--color-primary)' : 'var(--color-canvas)',
              color: current === p ? 'var(--color-on-primary)' : 'var(--color-ink)',
              fontSize: 14,
              fontWeight: 500,
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              transition: 'all 150ms ease',
            }}
          >
            {p}
          </button>
        )
      )}

      <button
        onClick={() => onChange(current + 1)}
        disabled={current === total}
        style={{
          width: 36,
          height: 36,
          borderRadius: 'var(--rounded-md)',
          border: '1px solid var(--color-hairline)',
          backgroundColor: 'var(--color-canvas)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          cursor: current === total ? 'not-allowed' : 'pointer',
          opacity: current === total ? 0.5 : 1,
          color: 'var(--color-ink)',
          transition: 'all 150ms ease',
        }}
      >
        <ChevronRight size={16} />
      </button>
    </div>
  )
}
